/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "proyecto.h"
#include "centro.h"

Servidor servidor;
HistorialTicket tickets;

int *
obtener_tiempo_respuesta_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;
	result = servidor.tiempo;

	return &result;
}

int *
solicitar_envio_gasolina_1_svc(char **argp, struct svc_req *rqstp)
{
   static int  result;
   HistorialTicket ticketBomba;
   int diferencialTiempo = 0;
   
   char* ip = (char*)malloc(sizeof(char)*100);
   if(ip == NULL){
      terminar("Error de asignacion de memoria: " );
   }
   
   char* nombreArchivoLog = (char*)obtenerNombreArchivoLog(servidor.nombreCentro);
   
   strcpy(ip,inet_ntoa(rqstp->rq_xprt->xp_raddr.sin_addr));
   
   ticketBomba = buscarTicket(tickets,ip);
   if((ticketBomba != NULL) || (ticketBomba->tiempoValidacion !=-1)){
      diferencialTiempo = servidor.tiempoSimulacion - ticketBomba->tiempoValidacion;
      if(diferencialTiempo<=30){
         if(servidor.inventario >= 38000){
            result = 1;
            servidor.inventario = servidor.inventario - 38000;
            escribirArchivoLog(nombreArchivoLog, "Verificacion de Estado del Ticket", 
                              servidor.tiempoSimulacion,servidor.inventario, *argp, "Valido");
            escribirArchivoLog(nombreArchivoLog, "Suministro", servidor.tiempoSimulacion,
                              servidor.inventario, *argp, "Ok");
         }else{
            result = 0;
            escribirArchivoLog(nombreArchivoLog, "Verificacion de Estado del Ticket", 
                              servidor.tiempoSimulacion,servidor.inventario, *argp, "Valido");
            escribirArchivoLog(nombreArchivoLog, "Suministro", servidor.tiempoSimulacion, 
                              servidor.inventario, *argp, "No Disponible");
         }
      }else{
         //escribirArchivoLog
         escribirArchivoLog(nombreArchivoLog, "Verificacion de Estado del Ticket",
                            servidor.tiempoSimulacion,servidor.inventario, *argp, "Vencido");
         result = 2;
      }
   }else{
      //escribirArchivoLog
      escribirArchivoLog(nombreArchivoLog, "Verificacion de Estado del Ticket",
                       servidor.tiempoSimulacion,servidor.inventario, *argp, "Inexistente");
      result = 2;
   }

   return &result;
}

int *
solicitar_reto_1_svc(char **argp, struct svc_req *rqstp)
{
   static int  result;
   
   pid_t hijoId;
   int status;
   
   char bufferLectura[512];
   char* parametro = "-s";
   
   char* tokenIgnorado = (char*)malloc(sizeof(char)*100);
   if(tokenIgnorado == NULL){
      terminar("Error de asignacion de memoria: " );
   }
   
   char* claveMD5 = (char*)malloc(sizeof(char)*100);
   if(claveMD5 == NULL){
      terminar("Error de asignacion de memoria: " );
   }
   
   char* parametroMD5 = (char*)malloc(sizeof(char)*100);
   if(parametroMD5 == NULL){
      terminar("Error de asignacion de memoria: " );
   }
   
   char* nombreArchivoLog = (char*)obtenerNombreArchivoLog(servidor.nombreCentro);
   
   char* reto = (char*)malloc(sizeof(char)*100);
   if(reto == NULL){
      terminar("Error de asignacion de memoria: " );
   }
   
   char* ip = (char*)malloc(sizeof(char)*100);
   if(ip == NULL){
      terminar("Error de asignacion de memoria: " );
   }
   
   int pipeMD5[2];
   if((pipe(pipeMD5)) < 0){
      errorFatal("Error: Creación de pipe para MD5 en solicitud de reto\n");
   }
   
   memset(bufferLectura, 0, sizeof(bufferLectura));
   
   srand(time(NULL));
   result = rand();
   
   sprintf(reto,"%d",result);
   
   strcpy(ip,inet_ntoa(rqstp->rq_xprt->xp_raddr.sin_addr));
   
   strcpy(parametroMD5,parametro);
   strcat(parametroMD5,reto);
   
   if((hijoId = fork()) < 0){
      errorFatal("Error: Fork para MD5 en solicitud de reto\n");
   }
      
   if(hijoId == 0){
      close(1);
      close(pipeMD5[0]);
      if(dup(pipeMD5[1]) < 0){
         errorFatal("Error: dup en solicitud de reto\n" );
      }
      
      if(execlp("md5","md5", parametroMD5, NULL)){
         errorFatal("Error: execlp en solicitud de reto\n" );
      }
       
      exit(0);
   }
      
   if(hijoId > 0){
      wait(&status);
      close(pipeMD5[1]);
      read(pipeMD5[0],bufferLectura,sizeof(bufferLectura));
      tokenIgnorado = strtok(bufferLectura,"=");
      claveMD5 = strtok(NULL,"=");
   }
   
   HistorialTicket ticketBombaCreado = buscarTicket(tickets, ip);
   if(ticketBombaCreado != NULL){
      ticketBombaCreado->claveMD5 = claveMD5;
      ticketBombaCreado->tiempoValidacion = -1;
   }else{
      tickets = insertarTicket(tickets, *argp, ip, claveMD5, -1);
   }
   //escribirArchivoLog    CASO Se incluye un nuevo ticket
   escribirArchivoLog(nombreArchivoLog, "Nuevo Ticket", servidor.tiempoSimulacion,
                  servidor.inventario, *argp, "Agregado");
   
   return &result;
}

int *
evaluar_respuesta_1_svc(char **argp, struct svc_req *rqstp)
{
   static int  result;
   
   char* ip = (char*)malloc(sizeof(char)*100);
   if(ip == NULL){
      terminar("Error de asignacion de memoria: " );
   }
   
   char* nombreArchivoLog = (char*)obtenerNombreArchivoLog(servidor.nombreCentro);
   
   strcpy(ip,inet_ntoa(rqstp->rq_xprt->xp_raddr.sin_addr));
   
   HistorialTicket ticketBomba = buscarTicket(tickets, ip); 
   
   if(ticketBomba != NULL){
      //Verificación de correspondencia de claves
      if(strcmp(ticketBomba->claveMD5,*argp) == 0){
         //escribirArchivoLog		CASO Autenticación exitosa
         escribirArchivoLog(nombreArchivoLog, "Autenticacion", servidor.tiempoSimulacion,
                           servidor.inventario, ip, "Exitosa");
         ticketBomba->tiempoValidacion = servidor.tiempoSimulacion;
         result = 1;
      }else{
         //escribirArchivoLog		CASO Autenticación fallida
         escribirArchivoLog(nombreArchivoLog, "Autenticacion", servidor.tiempoSimulacion,
                           servidor.inventario, ip, "Fallida");
         result = 0;
      }
   }else{
      mensajeError("Error: La Bomba no ha solicitado reto anteriormente\n");
      result = 0;
   }

   return &result;
}
