/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROYECTO_H_RPCGEN
#define _PROYECTO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PROY2 0x20039990
#define PROYECTO2_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define OBTENER_TIEMPO_RESPUESTA 1
extern  int * obtener_tiempo_respuesta_1(void *, CLIENT *);
extern  int * obtener_tiempo_respuesta_1_svc(void *, struct svc_req *);
#define SOLICITAR_ENVIO_GASOLINA 2
extern  int * solicitar_envio_gasolina_1(void *, CLIENT *);
extern  int * solicitar_envio_gasolina_1_svc(void *, struct svc_req *);
extern int proy2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OBTENER_TIEMPO_RESPUESTA 1
extern  int * obtener_tiempo_respuesta_1();
extern  int * obtener_tiempo_respuesta_1_svc();
#define SOLICITAR_ENVIO_GASOLINA 2
extern  int * solicitar_envio_gasolina_1();
extern  int * solicitar_envio_gasolina_1_svc();
extern int proy2_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROYECTO_H_RPCGEN */
